#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/database
- name: Run Database
  docker_container:
    name: my-db
    image: elliotmv/tp-devops-database
    networks:
      - name: network_one