#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/simple-api
- name: Run simple-api
  docker_container:
    name: my-api
    image: elliotmv/tp-devops-simple-api
    pull: always
    networks:
      - name: network_one