#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/front
- name: Run front
  docker_container:
    name: front
    image: elliotmv/tp-devops-front
    pull: always
    networks:
      - name: network_one