name: Build & Push docker image

on:
  workflow_run:
    workflows: ["Test backend"]
    types:
        - completed
    branches: [main]

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:simple-api"
          push: ${{ github.ref == 'refs/heads/main' }}
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:database"
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-database:latest

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:http-server"
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-http-server:latest

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:front"
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-front:latest
